#!/bin/bash

########################
##### instructions #####
########################

# copy this file to local-settings to override default values in run.sh
# define ${MACHINE1...n}
# define ${MACHINES}
# define ${BENCHMARK_OPTS} (name + config file)
# ${MACHINES} will be used for the defined ${BENCHMARK_OPTS} (no need to add them here)

###########################
##### remote settings #####
###########################

#USER=hazelcast
#KILL_JAVA_SUDO=true

#MACHINE1='212.175.226.222:1111'
#MACHINE2='212.175.226.222:2222'
#MACHINE3='212.175.226.222:3333'
#MACHINE4='212.175.226.222:4444'

#MACHINES="${MACHINE1} ${MACHINE2}"
#BENCHMARK_OPTS='2-nodes benchmark-2nodes.xml'

#MACHINES="${MACHINE1} ${MACHINE2} ${MACHINE3} ${MACHINE4}"
#BENCHMARK_OPTS='4-nodes benchmark-4nodes.xml'

##########################
##### local settings #####
##########################

#REPORTS_DIR=reports
#KILL_JAVA=no_idea

#MACHINE1='127.0.0.1'

#MACHINES="${MACHINE1}"
#BENCHMARK_OPTS='local local-benchmark.xml'
