#!/bin/bash

# copy this file to local-settings to override default values in run.sh

# remote settings

#MACHINE1='212.175.226.222:1111'
#MACHINE2='212.175.226.222:2222'
#MACHINE3='212.175.226.222:3333'
#MACHINE4='212.175.226.222:4444'
#MACHINES="${MACHINE1} ${MACHINE2} ${MACHINE3} ${MACHINE4}"
#BENCHMARK_OPTS="4-nodes benchmark-4nodes.xml ${MACHINE1}"
#USER=hazelcast

# local settings

#MACHINE1='127.0.0.1'
#MACHINES="${MACHINE1}"
#BENCHMARK_OPTS="local local-benchmark.xml ${MACHINE1}"
#REPORTS_DIR=reports
#KILL_JAVA=false